apiVersion: v1
kind: Service
metadata:
  name: bitcoin-app
  labels:
    app: bitcoin-app
spec:
  type: NodePort
  selector:
    app: bitcoin-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
